const SET_SHOWS = 'SET_SHOWS';
const GET_SHOWS_BY_PAGINATION = 'GET_SHOWS_BY_PAGINATION';
const SET_PAGINATION = 'SET_PAGINATION';

export {
  SET_SHOWS,
  GET_SHOWS_BY_PAGINATION,
  SET_PAGINATION
};
