const SET_SHOWS = 'SET_SHOWS';
const GET_SHOWS_BY_PAGINATION = 'GET_SHOWS_BY_PAGINATION';
const SET_PAGINATION = 'SET_PAGINATION';
const SET_IS_DIALOG_OPEN = 'SET_IS_DIALOG_OPEN';
const SET_SHOW_ID = 'SET_SHOW_ID';
const SET_SHOW_DETAILS = 'SET_SHOW_DETAILS';

export {
  SET_SHOWS,
  GET_SHOWS_BY_PAGINATION,
  SET_PAGINATION,
  SET_IS_DIALOG_OPEN,
  SET_SHOW_ID,
  SET_SHOW_DETAILS
};
